dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql -e 'CREATE DATABASE yii2_schemadump_test;'
  - psql -c 'create database yii2_schemadump_test;' -U postgres
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

before_script:
  - echo -e "[server]\nexplicit_defaults_for_timestamp=1" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
